projectceladon/MediaSDK_C2

c2_buffers/src/mfx_c2_frame_in.cpp
c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp

Release the handle returned after calling the
UnwrapNativeCodec2GrallocHandle function in time.

[c2][memory]Fixed some memory leak issues.

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

~~1. If OutputDelay less than sugguseted value from MFX, instead of returning error to C2, update the value.~~
2. Modify the default value of VP9 format from 10 to 11.

[c2][decode]Modify the buffer count of VP9 from 10 to 11

---

Android.bp
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_defs.h
mfx_c2_defs.mk

This change is to enable mediasdk codec2.0 plugin
on Android S.

Enable Codec2.0 on Android S

---

Android.bp
c2_store/src/mfx_c2_store.cpp

In case hardware is unavailable, don't load codec2.0 components.
Tracked-On: OAM-100214

Disable HW codec2.0 plugin if hardware is unavailable

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_msdk_debug.h
c2_utils/src/mfx_frame_constructor.cpp
c2_utils/src/mfx_va_frame_pool_allocator.cpp

This change includes,
1. Add 10bit yuv format support for main10 profile clips
2. Parse HDR static meta data from HEVC SEI.
Tracked-On: OAM-100284

Enable HDR video playback for HEVC Main10 profile

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp

case: android.media.cts.DecoderTest#testCodecResetsVP9WithSurface
This change fixes an issue which submitted same wrong bitstream
to oneVPL in a loop when decoding.
Tracked-On: OAM-100630

[c2][decode] Fix cts failure

---

c2_components/src/mfx_c2_decoder_component.cpp

This is a regressin issue introduced by commit
8303ef9b3e87ae59607dc086cf5b4ca6ac692959.
m_allocator can only be released at the end of
playback. Otherwise, m_allocator will be set to
nullptr in FreeDecoder() in some case and va frame
pool will not work corectly any more.
Mute the massive log messages in case of fetching
a nocached block.
Tracked-On: OAM-100685

Fixed video not playing issue

---

c2_store/hardware.intel.media.c2@1.0-service.rc
c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86.policy
c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86_64.policy

This change is to change domain user from root to mediacodec.
Otherwise, we will see below error messages and fail to start
codec2.0 service.
W init : type=1400 audit(0.0:534): avc: denied { transition }
for path="/vendor/bin/hw/hardware.intel.media.c2@1.0-service"
dev="dm-5" ino=101 scontext=u:r:init:s0 tcontext=u:r:su:s0
tclass=process permissive=0
Tracked-On:

Fix sepolicy issue in userbuild

---

c2_store/src/mfx_c2_service.cpp

OMX dependency in codec 2.0 is for debugging purpose.
Both OMX and Codec2.0 service can start individually.
It's weird to add OMX support in codec2.0.
Tracked-On: OAM-100794

Remove OMX dependency in codec2.0

---

c2_components/src/mfx_c2_decoder_component.cpp

case: android.media.cts.VideoEncoderTest#testGoogH264Flex360pWithIntraRefresh
When decoding using system memory, msdk always returns surface which is
unlocked, so removed if statement.
Tracked-On: OAM-100781

[c2][decode] Fixed an issue when decoding using system memory

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/src/mfx_c2_color_aspects_wrapper.cpp

android.media.cts.DecoderTest#testH264ColorAspects
android.media.cts.DecoderTest#testH265ColorAspects
android.media.cts.DecoderTest#testMPEG2ColorAspectsTV
The solution is to add configration for default
color apsects.
Tracked-On: OAM-101056

Fixed coloraspect related test cases

---

c2_buffers/include/mfx_c2_bitstream_in.h
c2_buffers/src/mfx_c2_bitstream_in.cpp
c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_frame_constructor.h
c2_utils/src/mfx_defs.cpp
c2_utils/src/mfx_frame_constructor.cpp
c2_utils/src/mfx_va_frame_pool_allocator.cpp

The root cause is that after decoder reset, video
decoding becomes async. The current bitstream data
is released in the previous decoding thread. Thus no
slice data is avaible and onevpl-gpu failed to copy
slice data.
The solution is to de-correlation between frameconstructor
and frame view. Let frame view is release after onevpl
finished the decoding of current bitstream.
Tracked-On: OAM-101053

Fix media cts testCodecResetsHEVCWithSurface

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/src/mfx_c2_utils.cpp

Root cause is that color aspects and pixel format
are set to the default values after seek.
Tracked-On: OAM-101068

Fixed dataspace changed issue after seek

---

c2_components/src/mfx_c2_decoder_component.cpp

adaptiveEosFlushSeek
eosFlushSeek
The root cause is that the video height is 16bit aligned
in onevpl but media cts is requesting the original input
frame size. The solution is to send the cropped width and
height (the final display width and height) to media cts
as the input frame size.
Tracked-On: OAM-101085

Fixed below failed cts in AdaptivePlaybackTest

---

c2_store/data/media_codecs_intel_c2_video.xml

case: android.media.cts.VideoEncoderTest#testOtherH265FlexMaxMin
android.media.cts.VideoEncoderTest#testOtherH265FlexMinMax
android.media.cts.VideoEncoderTest#testOtherH265FlexMinMin
Incorrect size will cause the driver to return an error.
Tracked-On: OAM-101096

[c2][encode] Adjust minimum and maximum sizes for encoding

---

c2_utils/src/mfx_defaults.cpp

case: android.media.cts.SurfaceEncodeTimestampTest
With AsyncDepth=1, mediaSDK will synchronize after encoding of
each frame. But with AsyncDepth=0, mediaSDK will set AsyncDepth
to larger than 1, synchronizing will be latency.
Tracked-On: OAM-101120

[c2][encode] Fixed SurfaceEncodeTimestampTest failures

---

c2_buffers/src/mfx_c2_frame_out.cpp
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_defs.h
c2_utils/src/mfx_defs.cpp
c2_utils/src/mfx_va_frame_pool_allocator.cpp

In case the decoded width parsed from bitstream is
not 16bit aligned, mediasdk or onevpl will force it
to 16byte aligned. Use display width and height to
create surface to avoid failure for below test case.
android.media.cts.DecodeAccuracyTest#testSurfaceViewLargerHeightDecodeAccuracy[23]
android.media.cts.DecodeAccuracyTest#testSurfaceViewLargerWidthDecodeAccuracy[23]
android.media.cts.DecodeAccuracyTest#testSurfaceViewVideoDecodeAccuracy[23]
Tracked-On: OAM-101186

Specical handling for odd video width

---

c2_buffers/src/mfx_c2_frame_out.cpp
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_defs.h
c2_utils/src/mfx_defs.cpp

Use stride got from GraphicView instead of video width
when system memory is used.
android.media.cts.ImageReaderDecoderTest#testOtherH264Image
android.media.cts.ImageReaderDecoderTest#testOtherH265Image
android.media.cts.ImageReaderDecoderTest#testOtherVP8Image
android.media.cts.ImageReaderDecoderTest#testOtherVP9Image
android.media.cts.ImageReaderDecoderTest#testOtherVP8ImageReader
Tracked-On: OAM-101198

Fixed stride issue when system memory is used

---

c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_c2_utils.h

case: android.media.cts.VideoCodecTest#testDynamicBitrateChangeHEVCNdkCBR
android.media.cts.VideoCodecTest#testDynamicBitrateChangeHEVCNdkVBR
android.media.cts.VideoCodecTest#testDynamicBitrateChangeVP9NdkCBR
android.media.cts.VideoCodecTest#testDynamicBitrateChangeVP9NdkVBR
If application sets NalHrdConformance option in mfxExtCodingOption
structure to ON, the only allowed bitrate control mode is VBR. If OFF,
all bitrate control modes are available.
Tracked-On: OAM-101252

[c2][encode] Fixed an issue which dynamic modification of bitrate failed

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp

InitSession will called multiple times, which will cause MFXload to
also be called multiple time. Each call overwrites the previous pointer
that was not freed so it makes a memory leak.
Tracked-On: OAM-102284

[c2][memory] Fixed memory leak in InitSession

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

This issue is to fix decoder timeout issue while dequeuing
input buffers. The root cause is that no input buffer returned
to codec2.0 framework in case of receving buffers with duplicated
timestamp.
Tracked-On: OAM-101354

Fixed decoder time out issue in case of duplicated timestamp

---

c2_buffers/src/mfx_c2_frame_in.cpp
c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_c2_utils.h
c2_utils/src/mfx_cmd_queue.cpp

This change includes,
1. Add API to query max and min resolution supported in encoder
2. Pass EOS flags if any in case codec2.0 failed unexpectedly
3. Return correct status for component reset
4. Add sanity check if invalid buffer sent to encoder
5. Refined bitrate control mode
6. Removed some tabs
Tracked-On: OAM-102693

Fixed some issues in VtsHalMediaC2V1_0

---

c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_encoder_component.cpp

The root cause is that the I frame interval is
not calculated correctly, thus only one IDR frame
is encoded for all the sequences, which results in
recorded video unable to seek.
Tracked-On: OAM-102237

Fixed recorded video not seek issue

---

c2_components/src/mfx_c2_decoder_component.cpp

13 testcases are passed out of 19 failures
with this changes.
Tracked-On: OAM-102797
Signed-off-by: Vasoya,Nikhilx <nikhilx.vasoya@intel.com>

[STS] fix for sts StagefrightTest failures

---

c2_components/src/mfx_c2_decoder_component.cpp

This reverts commit 2c652c7b1d56ff01a850cd90c92633de9a826e54.
Although surface_out is null when mfx_sts = MFX_ERR_MORE_DATA,
still expect output on next work.

Revert "[STS] fix for sts StagefrightTest failures"

---

mfx_c2_defs.mk

Enable DRM primary memory type in codec2.0
Tracked-On: OAM-101794

Enable DRM primary memory type in Android T

---

c2_utils/include/mfx_c2_utils.h
c2_utils/src/mfx_defs.cpp

cases:
android.mediav2.cts.CodecDecoderSurfaceTest#testFlushNative
android.mediav2.cts.CodecDecoderSurfaceTest#testSimpleDecodeToSurface
[0(c2.intel.av1.decoder_video/av01)]
The pitch should be width * 2 if fourcc is MFX_FOURCC_P010.
Tracked-On: OAM-103640

[c2][decoder] Caculate pitch by fourcc

---

c2_utils/src/mfx_c2_color_aspects_wrapper.cpp

cases:
android.mediav2.cts.DecoderColorAspectsTest[2(c2.intel.av1.decoder_video/av01_1_2_4)]
android.mediav2.cts.DecoderColorAspectsTest[10(c2.intel.av1.decoder_video/av01_1_8_1)]
android.mediav2.cts.DecoderColorAspectsTest[14(c2.intel.av1.decoder_video/av01_1_6_7)]
MSDK doesn't specify the color aspect for av1 so far.
Tracked-On: OAM-103721

[c2][decoder] Fixed av1 color aspect issue

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

cases:
android.media.decoder.cts.DecoderTest#testCodecResetsH264WithSurface android.media.decoder.cts.DecoderTest#testCodecResetsHEVCWithSurface
From Android T, Surfaces are no longer used when MediaCodec#stop() is called. 
https://android-review.googlesource.com/c/platform/frameworks/av/+/2098075 
Exit the loop when the surface may not be available.
Tracked-On: OAM-104001

[c2][decoder] Exit the loop when the surface may not be available

---

c2_components/src/mfx_c2_encoder_component.cpp

case:
android.mediav2.cts.EncodeDecodeAccuracyTest#testEncodeDecodeAccuracyRGB
With setting the default of bitrate mode to BITRATE_CONST and it will be not changed in the format by user, MediaCodecInfo.CodecCapabilities.isFormatSupported will return false.
Tracked-On: OAM-104427

[c2][decoder] Modify the default value of the bitrate mode

---

c2_components/src/mfx_c2_encoder_component.cpp

case:
android.mediav2.cts.EncodeDecodeAccuracyTest#testEncodeDecodeAccuracyRGB
With setting the default of bitrate mode to BITRATE_CONST and it will be not changed in the format by user, MediaCodecInfo.CodecCapabilities.isFormatSupported
will return false.
Tracked-On: OAM-104455

Modify the default value of the bitrate mode

---

c2_utils/src/mfx_defs.cpp

Added valid check for SurfacesPool in MFXGetFreeSurfaceIdx fixed VTS hal test VtsHalMediaC2V1_0TargetComponentTest
Tracked-On: OAM-104728

Added valid check for SurfacesPool.

---

c2_components/src/mfx_c2_decoder_component.cpp

In some case, the size of video buffer is incorrect set by framework. Need to check if the size is changed. and inform framework to change the buffer size.
Tracked-On: OAM-102924

Inform framework to update config once the buffer size is changed

---

c2_store/data/media_codecs_intel_c2_video.xml

Element 'Diagnostics': This element is not expected Against the schema: "/data/local/tmp/media_codecs.xsd" fixing vts_mediaCodecs_validate_test
Tracked-On: OAM-104733

Remove unsupported Diagnostics Element in xml

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

Add property "mediacodec2.dump.buffer" for triggering dumping buffer
setenforce 0
setprop mediacodec2.dump.buffer X
to dumping X frames buffer into /data/local/traces/decoder_frame.yuv
for instance,
setprop mediacodec2.dump.buffer 100
dumping 100 frame buffers.
Tracked-On: OAM-105271

Dumping decoded buffer

---

c2_components/include/mfx_c2_decoder_component.h

case: PerInstance/Codec2VideoDecHidlTest#AdaptiveDecodeTest/default_c2_intel_avc_decoder_1
Set the default value of m_outputPoolId back to BASIC_GRAPHIC.
Tracked-On: OAM-105462

[c2][decoder] Fixed Vts issue which fetch noncached blocks constantly

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_defs.h

related issue: OAM-105136
When the bitstream header is incomplete, component will cache a lot bitstream to find complete header info. In order to avoid excessive memory consumption, we reduce minimum input buffer size from 8M to 2M.
Tracked-On: OAM-105477

[c2][decoder] Reduce input buffer size

---

c2_components/src/mfx_c2_component.cpp

The issue with MultipleStartStopReset is when we do start()->reset()->start(), the state is in RUNNING state, so start() is returning the C2_BAD_STATE.
Added the functionality for reset() method in mfx_c2_component for fixing the issue with the VtsHalMediaC2 module.
Tracked-On: OAM-103591
Signed-off-by: gollarx <ratnakumarix.golla@intel.com>

Fix for Vts MultipleStartStopReset

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp

Fixed Vts issue which fetch noncached blocks constantly
Set the default value of m_outputPoolId back to BASIC_GRAPHIC.
As VTS call the component’s function directly(skip codec) from HAL. So that we set the outputPoolId to PLATFORM_START, it will use the BUFFERQUEUE allocator, but no surface was set. That’s the reason
igbp_id is 0 and igbp_slot is ~0(0xffffffff).
Tracked-On: OAM-105589
Signed-off-by: Yang, Dong <dong.yang@intel.com>
Signed-off-by: gollarx <ratnakumarix.golla@intel.com>

MediaSDK_C2 refactor regression.

---

c2_components/src/mfx_c2_encoder_component.cpp

Disable UNSUPPORTED PROFILE_HEVC_MAIN_10 as
For HEVC_MAIN10 profile, the bitdepth value should be 10. and currently, we don't support 10bit hevc encoding in mediasdk codec2.0.
Tracked-On: OAM-105730
Signed-off-by: Yang, Dong <dong.yang@intel.com>

Fix hevc testValidateProfileLevel

---

c2_components/src/mfx_c2_decoder_component.cpp

2M is used in Software Codec. and may cause memory overfllow in CTS. Reduce it to 1M.
HEVC required 64 aligned, AVC required 16 aligned. We keep the size 64 aligned for all formats
Tracked-On: OAM-105770

Change the MinInputBufferSize to 1M and Make the size is aligned with 64

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_defs.h

Using 2M is with Software Codec calculation causing memory overfllow in CTS. Reduce it to 1M.
Tracked-On: OAM-105273
Signed-off-by: vdanix <vishwanathx.dani@intel.com>

Change the MinInputBufferSize to 1M

---

c2_components/src/mfx_c2_encoder_component.cpp

Once the type is not H264 or H265, and the params is valid. Just set framerate.
Tracked-On: OAM-105975

Remove the unnecessary check in updating params

---

c2_buffers/include/mfx_c2_frame_in.h

coverity tool scan this uninitialzied pointer,
which caused uninitialized value mfx_frame_in.m_pMfxFrameSurface used when calling ~MfxC2FrameIn.
Tracked-On: OAM-108680

Fix uninitialized pointer issue

---

c2_components/src/mfx_c2_decoder_component.cpp

case: android.media.codec.cts.MediaCodecCapabilitiesTest# testGetMaxSupportedInstances
Reduced the default value of max picture size on av1 decoder.
Tracked-On: OAM-108707

[c2][decoder] fix an issue create av1 decoder using too much memory

---

c2_components/src/mfx_c2_encoder_component.cpp

For fixing Coverity issue(Big parameter passed by value), we used reference instead of value. But found a dangling reference issue. So revert it.
Tracked-On: OAM-108736

[c2][encoder] Fixed a dangling reference issue

---

mfx_c2_defs.mk

Update the API to 2.8
Change the API version to 2.8 for multi-adapter
Tracked-On: OAM-110480

Update the API to 2.8

---

c2_components/src/mfx_c2_decoder_component.cpp

TC: testClearKeyPlaybackMpeg2ts is failing because Video playback is not happening due to the commit: 984a09e10f0820b43cddfbe9810dc4508c8b0794 as it is clearing the each incoming frame index's input buffer in the decoder component.
Instead of clearing the input buffers initialize the m_uInputDelay in decoder.
Tracked-On: OAM-106762

Revert clearing the input buffers in decoder

---

c2_components/src/mfx_c2_decoder_component.cpp

cases:
android.media.decoder.cts.AdaptivePlaybackTest#test_adaptiveEosFlushSeek[0(c2.intel.avc.decoder)] android.media.decoder.cts.AdaptivePlaybackTest#test_eosFlushSeek[0(c2.intel.avc.decoder)]
Maintain the consistency of m_size modification during GetPictureSize and WaitWork.
Tracked-On: OAM-110802

[c2][decoder] Fixed some AdaptivePlaybackTest failures

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_store/src/mfx_c2_service.cpp
c2_utils/src/mfx_c2_utils.cpp

1. Time of check time of use (TOCTOU)
2. Uncaught exception
3. Calling usleep(1000U) is only useful for its return value, which is ignored
Tracked-On: OAM-110566

Fixed few static analysis issues

---

c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86.policy
c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86_64.policy

getgid and getegid are invoked in libva 2.19 release for security_getenv so add them into allow list, otherwise, libva will failed to load driver.
Tracked-On: OAM-111675

Add getgid and getegid into allow list of seccomp

---

c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_gralloc1.h
c2_utils/include/mfx_gralloc4.h
c2_utils/include/mfx_gralloc_interface.h
c2_utils/src/mfx_gralloc1.cpp
c2_utils/src/mfx_gralloc4.cpp
mfx_c2_defs.mk

From Android U, the get function of IMapper4 will check whether the buffer handle is reserved. So we need to call importBuffer before getting the buffer's info.
https://chromium-review.googlesource.com/c/chromiumos/platform/minigbm/+/3433121
Tracked-On: OAM-111738

[c2][encoder] Fixed the gralloc4 not working on Android U

---

c2_components/src/mfx_c2_decoder_component.cpp

The reason is that video 4K thumbnail optimization own all buffers, but AnTuTu needs to get the buffer and convert the YUV to RGB. The video buffers may re-write when decoding the thumbnails. This caused video frames mismatch issue in AnTuTu video tests. We disable this 4K video thumbnail optimization to resovle it.
Tracked-On: OAM-112346

Disable the optimization for 4K thumbnail generation

---

c2_components/src/mfx_c2_decoder_component.cpp

case:testFlushNative[39(c2.intel.vp9.decoder_video/x-vnd.on2.vp9)]
The error comes from onevpl when we get multiple flushing request in decoding. The root is that vp9 don't need process the bs which the flag is config.
Tracked-On: OAM-112305

[c2][decoder] Fixed the ERR_UNDEFINED_BEHAVIOR error in vp9 decoding

---

c2_store/src/mfx_c2_service.cpp
c2_utils/src/mfx_gralloc1.cpp
c2_utils/src/mfx_va_frame_pool_allocator.cpp
plugin_store/src/mfx_c2_buffer_queue.cpp

1. Uncaught exception (UNCAUGHT_EXCEPT).
2. Unchecked return value (CHECKED_RETURN).
3. Assigning value MFX_ERR_INVALID_HANDLE to mfx_res here, but that stored value is overwritten before it can be used.
4. Variable c2Handle going out of scope leaks the storage it points to.
5. Dereferencing null pointer outBuffer.
Tracked-On: OAM-112437

Fixed few static analysis issues<2>

---

plugin_store/src/mfx_c2_buffer_queue.cpp

* Fix a compilation error caused by a wrong name
Tracked-On: OAM-112861

Fix a compilation error caused by a wrong name

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

Add a parameter to AOSP for setting the buffer useage of output memory Once it is set as CPU_READ, force to use system memory, instead of video memory.
Remove the valiable m_consumerUsage which is only set as default.
Tracked-On: OAM-111768

Add a param for setting output usage.

---

c2_components/src/mfx_c2_decoder_component.cpp
plugin_store/src/mfx_c2_buffer_queue.cpp

case: android.graphics.cts.ImageDecoderTest#testDecode10BitHeif
When decoding the image, the timestamp is always 0, so it is excluded.
Tracked-On: OAM-113061

[c2][decoder] Duplicate frame check exclude 0

---

c2_components/src/mfx_c2_decoder_component.cpp

case: android.media.decoder.cts.DecoderTest#testH265ColorAspects
When the color aspects didn't read from bitstream, we should use the default value which from framework.
Tracked-On: OAM-113560

[c2][decoder] Fixed a regression with color aspects

---

c2_components/Android.bp
c2_components/include/mfx_c2_component.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/Android.bp
c2_utils/include/mfx_defs.h
c2_utils/include/mfx_dev.h
c2_utils/include/mfx_va_allocator.h
c2_utils/src/mfx_dev_va.cpp
c2_utils/src/mfx_va_allocator.cpp

1\ Enable ONEVPL_EXPERIMENTAL for init dGPU session and get deviceId 2\ According to device id to judge if it is dGPU or iGPU 3\ dGPU deviceid range: 0x5600 < deviceId < 0x56B3 4\ After initializing dGPU, reset RateControl for dGPU. 5\ Set buffer Tile4 for dGPU and Y-Tile for iGPU
Tracked-On: OAM-112744

Enable dGPU for decoder and encoder

---

c2_components/src/mfx_c2_encoder_component.cpp

dGPU only support CQP rate-control.
whatever framework set, force to set CQP.
Tracked-On: OAM-113684

Force to set CQP rate control on dGPU

---

c2_components/include/mfx_c2_component.h
c2_components/src/mfx_c2_component.cpp
c2_store/src/mfx_c2_store.cpp
c2_utils/include/mfx_c2_components_monitor.h
c2_utils/include/mfx_c2_xml_parser.h
c2_utils/include/mfx_defs.h
c2_utils/src/mfx_c2_components_monitor.cpp
c2_utils/src/mfx_c2_xml_parser.cpp

cases:
testLowerPriorityProcessFailsToReclaimResources
testHigherPriorityProcessReclaimsResources
* The default concurrent instances is 32, you can configure it in xml file if you want. 
(e. g. `<Limit name="concurrent-instances" max="16" />`)
Tracked-On: OAM-112660

[c2][store] Add concurrent-instances support and fixed cts failures

---

c2_components/src/mfx_c2_component.cpp

case: android.media.decoder.cts.AdaptivePlaybackTest#test_adaptiveReconfigDrc
In some cases, codec will do start and stop many times even for one codec instance,
then it leads to exceed maximum codec instance number.
Moving to constructructor/desctructor can resolve the problem.
Tracked-On: OAM-118206

[c2][store] Fixed some cts failures caused by monitor

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

case: android.mediav2.cts.CodecDecoderSurfaceTest#
testSimpleDecodeToSurface[2(c2.intel.av1.decoder_video/av01)]
Some cases will fail due to lack of the 10-bit format advertised for codec2.
Tracked-On: OAM-118544

[c2][decoder] Add some color format support for codec2

---

c2_components/src/mfx_c2_component.cpp

When status is not STOPPED. invokeing stop for reset.
Tracked-On: OAM-118462

Decoder/Encoder Reset method implement for VTS

---

c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_encoder_component.cpp

case: android.mediav2.cts.EncoderProfileLevelTest#
testValidateProfileLevel[8_c2.intel.avc.encoder_video/
avc_128kbps_176x144_15fps_yuv420flexible_2_0-bframes]
For Level 1b, we want to update the level anyway,
so we set it to next level in these cases
Tracked-On: OAM-118631

Fix CTS issue: Level information expected at least 2 but got 1

---

c2_utils/src/mfx_c2_utils.cpp

cases:
android.media.decoder.cts.ImageReaderDecoderTest#decodeTest [70_video/hevc_c2.intel.hevc.decoder_144x136_10bit_swirl_image]
Using HAL_PIXEL_FORMAT_YCBCR_P010 instead of HAL_PIXEL_FORMAT_P010_INTEL when using system buffer.
Tracked-On: OAM-118915

[c2][decoder] Fixed the issue incorrect data with 10-bit system memory

---

c2_components/src/mfx_c2_decoder_component.cpp

CTS test cases below required level 1.4
android.mediav2.cts.CodecDecoderValidationTest#testDecodeAndValidate[6_c2.intel.av1.decoder_video/av01] android.mediav2.cts.CodecDecoderValidationTest#testDecodeAndValidate[8_c2.intel.av1.decoder_video/av01]
Tracked-On: OAM-118636

Add profile level 1.3.1 and 1.4 for AV1 decoder.

---

c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_c2_utils.h

Some CTS tests of android.videocodec.cts.VideoEncoderMaxBFrameTest# testMaxBFrameSupport failed with "Number of BFrames in a SubGOP exceeds maximum number of BFrames configured".
Cause is for HEVC encode, in onevpl-intel-gpu mfxExtCodingOption3 ->GPB is set to "on" by default, which makes GPB frames are used instead of P frames. In CTS test, GPB frames are considered B frames.
Solution is for HEVC encode, set mfxExtCodingOption3->GPB to "off" in parameter to use P frames not GPB frames.
Tracked-On: OAM-118626

[encode] Fix CTS fail of max B frames exceed configured number

---

c2_components/src/mfx_c2_encoder_component.cpp

HAL_PIXEL_FORMAT_YCBCR_P010:android.mediav2.cts.CodecEncoderSurfaceTest#testSimpleEncodeFromSurface [210_c2.intel.vp9.encoder_video/x-vnd.on2.vp9_c2.android.vp9.decoder_video/ x-vnd.on2.vp9_512kbps_30fps_surfaceabgr2101010_tonemapno_persistentsurface]
HAL_PIXEL_FORMAT_P010_INTEL:android.mediav2.cts.CodecEncoderSurfaceTest#testSimpleEncodeFromSurface [208_c2.intel.vp9.encoder_video/x-vnd.on2.vp9_c2.intel.vp9.decoder_video/ x-vnd.on2.vp9_512kbps_30fps_surfaceabgr2101010_tonemapno_persistentsurface]
Tracked-On: OAM-118635

[c2][encoder] Disable VP9 Encoder 10bit support

---

c2_buffers/src/mfx_c2_frame_in.cpp
c2_buffers/src/mfx_c2_frame_out.cpp
c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_c2_utils.h
c2_utils/include/mfx_defs.h
c2_utils/src/mfx_c2_utils.cpp
c2_utils/src/mfx_defs.cpp

The same with https://github.com/projectceladon/MediaSDK_C2/pull/149, Closed and couldn't be reopened(force push)
Format: HAL_PIXEL_FORMAT_YCBCR_P010
android.mediav2.cts.CodecEncoderSurfaceTest#testSimpleEncodeFromSurface [210_c2.intel.vp9.encoder_video/x-vnd.on2.vp9_c2.android.vp9.decoder_video/ x-vnd.on2.vp9_512kbps_30fps_surfaceabgr2101010_tonemapno_persistentsurface]
Format: HAL_PIXEL_FORMAT_P010_INTEL
android.mediav2.cts.CodecEncoderSurfaceTest#testSimpleEncodeFromSurface[ 208_c2.intel.vp9.encoder_video/x-vnd.on2.vp9_c2.intel.vp9.decoder_video/ x-vnd.on2.vp9_512kbps_30fps_surfaceabgr2101010_tonemapno_persistentsurface]
Tracked-On: OAM-120369

[c2][encoder] Add p010 format support in encoder component

---

c2_components/src/mfx_c2_encoder_component.cpp

This reverts commit 9787058103e452c007fae774c52804eb3f9ae433. We revert this commit because we have to support vp9 10bit to pass some performance test.
Case:
android.mediapc.cts.MultiTranscoderPerfTest#test4kHbd[10_Pair{video/hevc c2.intel.hevc.decoder} _Pair{video/x-vnd.on2.vp9 c2.intel.vp9.encoder}_true]
Tracked-On: OAM-120841

Revert "[c2][encoder] Disable VP9 Encoder 10bit support"

---

c2_buffers/include/mfx_c2_bitstream_in.h
c2_buffers/src/mfx_c2_bitstream_in.cpp
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/include/mfx_frame_constructor.h
c2_utils/src/mfx_frame_constructor.cpp

CTS test of android.mediav2.cts.CodecDecoderTest#testFlush run failed with "Decoder output is not consistent across runs".
Cause: For AV1 decode, csd info is removed during flush.
Solution: Add csd config in the end of flush function.
Tracked-On: OAM-119036

[c2][decoder] Re-configure csd after flush for AV1 decode

---

c2_components/src/mfx_c2_encoder_component.cpp

cases: NonStdInputs/Codec2ComponentInputTests
Return empty work When encounter null input buffer.
Tracked-On: OAM-119798

[c2][encoder] Fixed VTS falures

---

c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_encoder_component.cpp

This reverts commit 6063a43f241ac01fc7ba5a7a0504b43956124a4a. This commit has caused some CTS tests to fail.
case:android.media.recorder.cts.MediaRecorderTest#testProfileAvcBaselineLevel1
Tracked-On: OAM-119037

Revert "Fix CTS issue: Level information expected at least 2 but got 1"

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp

case:
testHDRDisplayCapabilities[6_video/x-vnd.on2.vp9_c2.intel.vp9.decoder] testHDRDisplayCapabilities[7_video/x-vnd.on2.vp9_c2.intel.vp9.encoder]
Temporarily remove 10-bit HDR advertised support until we actually support them.
Tracked-On: OAM-118634

[c2][hdr] Remove 10-bit HDR/HDR+ advertised support for framework

---

c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_encoder_component.cpp

Add PROFILE_HEVC_MAIN_10 profile for HEVC encoder to support 10 bit / HDR encode.

[c2][encoder] Support 10 bit / HDR encode for HEVC

---

c2_components/src/mfx_c2_decoder_component.cpp

cases: testDefaultOutputColorFormat
Onevpl will change format according to bitstream,
but Google hopes the default of output is 8-bit
when the key "KEY_COLOR_FORMAT" is not set.
So we set back to 8-bit after decodeDecodeHeader
when m_pixelFormat->value wasn't changed by framework.
Tracked-On: OAM-119832

[c2][decoder] Set default output to 8-bit pixel format

---

c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_encoder_component.cpp
c2_store/src/mfx_c2_store.cpp
c2_utils/include/mfx_c2_utils.h
c2_utils/src/mfx_c2_utils.cpp

Changes include:
- Add ENCODER_AV1 type in MfxC2EncoderComponent
- Register it to ComponentsRegistry
- Define profiles and levels for AV1
- Add mapping of profiles and levels between Mfx and Android
Tests Done:
- Ran CtsMediaEncoderTestCases android.media.encoder.cts.VideoEncoderTest
Tracked-On: OAM-121126

Enable av1 encoder in c2_components

---

c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_defs.h
c2_utils/include/mfx_gralloc1.h
c2_utils/include/mfx_gralloc4.h
c2_utils/include/mfx_gralloc_interface.h
c2_utils/src/mfx_gralloc1.cpp
c2_utils/src/mfx_gralloc4.cpp

Start with Android U, the get function of IMapper4 will check whether the buffer handle is reserved.
 
1. Call importBuffer to preserve handle before getting the buffer's info.
2. Call freeBuffer at the end.
3. Switch to use gralloc4.
Tracked-On: OAM-112928

[c2][gralloc4] Fixed gralloc4 regression on Android U

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

Improve performance when CPU need access decode surface
1. Send consumer usage from framework, allocate system/video memory according to
consumer usage.
2. If cpu read often, use minigbm allocate linear NV12 buffer, and C2 send this
"system buffer" to OneVPL, OneVPL internally allocate NV12 buffer for decoding using
vaapi and copy this internal buffer to linear surface internally
Tracked-On: OAM-124103

Improve performance when CPU need access decode surface 

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

run ats -a x86_6 -m GtsExoPlayerTestCases -t
com.google.android.exoplayer.gts.CommonEncryptionDrmTest#cencSchemeTypeV184
The root cause is that the resolution changed processing flow was triggered when decoding the last input bitstream with the same timestamp but different frame index. At this point, the input must be processed as an independent frame.
Tracked-On: OAM-118988

Resolve Widevine L3 cencSchemeTypeV18 failed

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

As driver doesn't support decode 10bit bitsteam to 8 bit frames
directly. Previous solution of changing frame info to 8-bit does
not work. Revert the commit and use VPP to convert 10 bit frames
to 8 bit.
Tracked-On: OAM-122766
Signed-off-by: Lina Sun <lina.sun@intel.com>Start with Android U, the get function of IMapper4

Use VPP for 10 bit to 8 bit frames conversion 

---

c2_utils/src/mfx_frame_constructor.cpp

std::make_shared will throw the std::bad_alloc exception rather than return nullptr. 
Here just remove the logically dead code for the coverity issue.
Tracked-On: OAM-123225

[c2][coverity] Fix coverity issue CID 349680

---

c2_utils/src/mfx_gralloc1.cpp

CID 398855: 'Constant' variable guards dead code
Refer to the implementation of importBuffer in minigbm: hardware/intel/external/minigbm-intel/cros_gralloc/gralloc1/cros_gralloc1_module.cc int32_t CrosGralloc1::importBuffer(const buffer_handle_t rawHandle, buffer_handle_t *outBuffer)
Tracked-On: OAM-126428

Fix coverity issue CID 398855

---

c2_buffers/src/mfx_c2_frame_in.cpp
c2_components/include/mfx_c2_component.h
c2_components/include/mfx_c2_decoder_component.h
c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp
c2_store/seccomp_policy/android.hardware.media.c2@1.0-arm.policy
c2_store/seccomp_policy/android.hardware.media.c2@1.0-arm64.policy
c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86.policy
c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86_64.policy
c2_store/src/mfx_c2_store.cpp
c2_utils/include/mfx_c2_defs.h
c2_utils/include/mfx_c2_utils.h
c2_utils/include/mfx_c2_xml_parser.h
c2_utils/include/mfx_debug.h
c2_utils/src/mfx_c2_utils.cpp
c2_utils/src/mfx_c2_xml_parser.cpp

Add dump functions for encoder/decoder.
For encoder & decoder dump be configured in media_codecs_intel_c2_video.xml.
Tracked-On: OAM-124732
Signed-off-by: Lina Sun <lina.sun@intel.com>

Add dump functions for encoder/decoder

---

c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/src/mfx_defaults.cpp

[c2][encoder] Fix AV1 encoder issue
Fix AV1 encode issue of "Encoder configure failed" and test be
always waiting and can not run to end when running ffmpeg.
"Encoder configure failed" is because in mfx_set_RateControlMethod
function AV1 encoder case in not handled.
Test always wait and can't run to end is because GopRefDist is not
set when initializing AV1 encoder, default value of 8 from vpl is
used, which caused mediasdk_c2 can't send work done notification
to framework codec, so framework codec can't queue more works after
queuing initial 4 works.
Besides, use PROFILE_AV1_0 & LEVEL_AV1_5_3 as default AV1 encoder
profile & level instead of PROFILE_AV1_0 & LEVEL_AV1_7_3, as the
latter can not work.
Tracked-On: OAM-124081
Signed-off-by: Lina Sun <lina.sun@intel.com>

Fix AV1 encode issue

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_utils/Android.bp
c2_utils/include/mfx_intel_device.h
c2_utils/src/mfx_c2_utils.cpp
c2_utils/src/mfx_intel_device.cpp

In hybrid GPU case, video decoder could be iGPU and the coded images would be consumed by dGPU. Unfortunately, it's likely that we can hardly find a tiling format supported by both of them. To achieve best compatibility and make our life better, simply use linear buffers for decoded images.
By setting CPU_READ and CPU_WRITE flags, we force OneVPL to allocate internal buffers and blit decoded content to external buffers. In this way we can work around hardware limitation that DG2 cannot decode to linear buffers.
We will detect the GPU group type and decide whether to use linear buffers or not.
Tracked-On: OAM-126399

Enforce linear buffer for decoding in the case of hybrid-GPU

---

c2_buffers/include/mfx_c2_frame_in.h
c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp
c2_store/src/mfx_c2_store.cpp
c2_utils/include/mfx_pool.h
c2_utils/src/mfx_gralloc4.cpp

Included type:
Big parameter passed by value
Resource leak
COPY_INSTEAD_OF_MOVE
Rule of three
Tracked-On: OAM-128155

Fix Coverity issues

---

c2_components/src/mfx_c2_encoder_component.cpp

Some tests of testResolutionSupport in CtsMediaV2TestCases failed because encoder does not support identical size ranges, make encoder supported height range and width range identical.
Tracked-On: OAM-129545

Make encoder support identical size ranges for width and height

---

c2_components/src/mfx_c2_decoder_component.cpp

From Android 15, Buffer pool use IGBA instead of BufferQueue. IGBA will strictly limit the number of buffers that can be allocated. We added an extra buffer cache to prevent stucking when call fetchGraphicBlock during resolution changes.
Tracked-On: OAM-128843

Fixed a stuck issue when resolution changes

---

c2_components/src/mfx_c2_decoder_component.cpp

Fix detach surface cts test run timeout issue
The issue is detach surface cts test run timeout, cause is it
keeps reallocating surface when the allocated surface is not in
cached buffer pool. After removing the InCache() limitation,
sometimes we get a locked block which is still used by onevpl and
will cause random fail.
Solution is 1) Remove code to check if allocated surfce is in
cache. 2) For detached surface situation, when get locked surface
we keep fetching new surface from framework until we get an
unlocked one.
Tracked-On: OAM-129505

Fix detach surface cts test run timeout issue

---

c2_components/src/mfx_c2_decoder_component.cpp

Due to secure bitstreams lack FLAG_CODEC_CONFIG, new header is not saved.
This may cause problem of attaching the wrong header during RESET.
- Revert flag handling to avoid affecting normal decoders.
Tracked-On: OAM-130988

Fix cts regression

---

c2_components/src/mfx_c2_decoder_component.cpp

Enable dynamic ColorAspect and bit-depth changes
For H264 and H265 format,
1/ Use the same resolution event for ColorAspect and bit-depth
2/ Reset bitstream for re-appending SPS/PPS header once
ColorAspect and bit-depth is changed
For VP9 and AV1
1/ Re-init VPL decoder once a new flag bitstream arrived
2/ setting ColorAspect also for VP9

Reset bitstream for re-append SPS/PPS header

---

c2_components/include/mfx_c2_encoder_component.h
c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_c2_enc_minlevel.h
c2_utils/src/mfx_c2_enc_minlevel.cpp

For level which doesn't match bitrate, framerate, width, height we will adjust it to minLevel manually.
Tracked-On: OAM-130529

Fix EncoderLevelTest

---

c2_components/src/mfx_c2_decoder_component.cpp
c2_components/src/mfx_c2_encoder_component.cpp
c2_utils/include/mfx_c2_defs.h

Because of no sepolicy for data dump related properties, lots of logs printed during codec, like: W libc : Access denied finding property "c2.decoder.dump.output.number".
So add sepolicy and rename data dump related properties per sepolicy requirement.
Tracked-On: OAM-131307

Rename data dump related properties per sepolicy requirement

---

c2_components/src/mfx_c2_decoder_component.cpp

6244680 Dereference before null check
6244688 Uninitialized scalar variable
Tracked-On: OAM-131369

Fix Coverity issues WW13.4

---

c2_components/include/mfx_c2_decoder_component.h
c2_components/src/mfx_c2_decoder_component.cpp

In resolution case, bitstream should not be reset. Only reset bitstream for ColorAspect and BitDepth changes
Tracked-On: OAM-131347

Only reset bitstream for ColorAspect and BitDepth changes
