Android.mk, c2_store/Android.bp, c2_store/manifest_media_c2_V1_0_default.xml, c2_store/manifest_media_c2_V1_1_default.xml, c2_store/manifest_media_c2_V1_2_default.xml, c2_store/seccomp_policy/android.hardware.media.c2@1.0-arm.policy, c2_store/seccomp_policy/android.hardware.media.c2@1.0-arm64.policy, c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86.policy, c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86_64.policy, c2_store/src/mfx_c2_service.cpp, c2_store/src/mfx_c2_store.cpp
This change includes codec2.0 sepolicy.
Tracked-On: OAM-100150
=> Add policy for codec2.0

c2_buffers/include/mfx_c2_frame_in.h, c2_buffers/src/mfx_c2_frame_in.cpp, c2_buffers/src/mfx_c2_frame_out.cpp, c2_components/include/mfx_c2_encoder_component.h, c2_components/src/mfx_c2_encoder_component.cpp, c2_store/data/media_codecs_intel_c2_video.xml, c2_utils/include/mfx_defs.h, c2_utils/src/mfx_defs.cpp
This change includes:
1. Add 16byte alignment for buffer allocation
2. Optimize buffer management with suggested
buffer count.
Tracked-On: OAM-100215
=> Fix camera recording issue

c2_components/src/mfx_c2_decoder_component.cpp
1. Check whether the BQ allocator has a surface, if No we cannot use MFX_IOPATTERN_OUT_VIDEO_MEMORY mode.
2. Same as DecodeHeader, MSDK will call the function av1_native_profile_to_mfx_profile to change CodecProfile in Init().
Tracked-On: OAM-102025
=> [c2][decoder] Fixed some issues for decoder

c2_components/src/mfx_c2_decoder_component.cpp
case:android.media.cts.AdaptivePlaybackTest#testAV1_adaptiveEosFlushSeek
android.media.cts.AdaptivePlaybackTest#testAV1_eosFlushSeek
Av1 decoder requires more reference frame buffers than other formats.
So we increase the count of frame data.
Tracked-On: OAM-102513
=> [c2][decode] Fixed an issue which insufficient memory for av1 decoding

c2_components/include/mfx_c2_encoder_component.h, c2_components/src/mfx_c2_decoder_component.cpp, c2_components/src/mfx_c2_encoder_component.cpp, c2_utils/include/mfx_c2_utils.h
android.mediav2.cts.EncoderColorAspectsTest#testColorAspects
Tracked-On: OAM-102737
=> Add color aspect support in video encoder

c2_store/Android.bp, mfx_c2_defs.mk
Port the bsp_diff patches introduced in Android-T to corresponding github projects
=> Android T patches

c2_components/src/mfx_c2_decoder_component.cpp
[Test No merge ] This reverts commit 2c652c7b1d56ff01a850cd90c92633de9a826e54.
=> Revert "[STS] fix for sts StagefrightTest failures"

c2_components/src/mfx_c2_decoder_component.cpp
cases: android.mediav2.cts.CodecDecoderSurfaceTest#testFlushNative
1. Av1 don't need the bs which flag is config.
2. Fixed av1 always fetch a noncatched block issue.
Tracked-On: OAM-103409
=> [c2][decoder] Fixed av1 decoding failed issues

c2_components/src/mfx_c2_decoder_component.cpp
case: widevineH264AdaptiveWithRendererDisablingV18
1. prevent deleting bs which in use.
2. when oneVPL returns an error of resolution change, it is not necessarily the width or height has changed. however, we reinit the codec.
3. when deleting a work if it is not found, do not return a fatal error directly.
Tracked-On: OAM-104374
=> [c2][decoder] Fixed some issues when oneVPL returns resolution change

c2_components/src/mfx_c2_decoder_component.cpp, c2_components/src/mfx_c2_encoder_component.cpp, c2_components/src/mfx_c2_vpp_wrapp.cpp, c2_store/src/mfx_c2_service.cpp, c2_utils/include/mfx_c2_utils.h, c2_utils/include/mfx_cmd_queue.h, c2_utils/include/mfx_pool.h, c2_utils/src/mfx_c2_utils.cpp, c2_utils/src/mfx_cmd_queue.cpp, c2_utils/src/mfx_va_allocator.cpp, c2_utils/src/mfx_va_frame_pool_allocator.cpp
issues summary: Uncheck return; self assign; pass nullpointer...;
Tracked-On: OAM-105553
=> Fix MediaSDK_C2 Coverity issues for Master branch

c2_utils/include/mfx_pool.h
=> Fixed failed to play video

c2_components/Android.mk, c2_components/include/mfx_c2_decoder_component.h, c2_components/src/mfx_c2_decoder_component.cpp, c2_components/src/mfx_c2_encoder_component.cpp, c2_utils/Android.bp, c2_utils/Android.mk, c2_utils/include/mfx_defs.h, c2_utils/include/mfx_gralloc1.h, c2_utils/include/mfx_gralloc4.h, c2_utils/include/mfx_gralloc_instance.h, c2_utils/include/mfx_gralloc_interface.h, c2_utils/include/mfx_va_allocator.h, c2_utils/include/mfx_va_frame_pool_allocator.h, c2_utils/src/mfx_gralloc1.cpp, c2_utils/src/mfx_gralloc4.cpp, c2_utils/src/mfx_gralloc_instance.cpp, c2_utils/src/mfx_va_allocator.cpp, c2_utils/src/mfx_va_frame_pool_allocator.cpp
1.add support for gralloc4
2.switch to using gralloc4
3.please use MfxGrallocInstance to call
Tracked-On: OAM-110892
=> [c2][gralloc] Add support for Gralloc4

c2_utils/src/mfx_va_allocator.cpp
This change is to replace VASurfaceAttribExternalBuffers with VADRMPRIMESurfaceDescriptor in va surface creation. With VADRMPRIMESurfaceDescriptor, the tile info can be specified explicitly and sent to media driver.
width iGPU, tileY is being used by default and there is no need to set this info, but with dGPU, tile info should be set.
Tracked-On: OAM-108862
=> Use VADRMPRIMESurfaceDescriptor to create surface

security.md
* Upload a security disclaimer
Tracked-On: OAM-111792
=> Upload a security disclaimer

c2_utils/src/mfx_va_allocator.cpp
drm_format_modifier is assigned NONE when encoding.
Tracked-On: OAM-111860
=> [c2][encoder] Fixed the issue scrcpy failure

Android.bp, c2_utils/Android.bp, mfx_c2.go
Reference the corresponding include according to different versions
Tracked-On: OAM-113239
=> [c2][build] Fixed a compilation issue with Android version compatibility

c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86.policy, c2_store/seccomp_policy/android.hardware.media.c2@1.0-x86_64.policy, plugin_store/src/mfx_c2_buffer_queue.cpp
Add mkdirat permission in policy file
Tracked-On: OAM-113414
=> [c2][policy] Fixed an issue that "blocked syscall: mkdirat" was reported on smr0

c2_store/include/mfx_c2_store.h, c2_utils/Android.bp, fuzzer/Android.bp, fuzzer/README.md, fuzzer/mfx_c2_dec_fuzzer.cpp, fuzzer/mfx_c2_dec_fuzzer.h
* Add fuzzer support
Tracked-On: OAM-112331
=> [c2][fuzzer] Add fuzzer support

c2_components/src/mfx_c2_encoder_component.cpp
case: android.mediav2.cts.CodecEncoderSurfaceTest#
testSimpleEncodeFromSurface[|Native][*_c2.intel.*.encoder_video/*_c2.intel.*.decoder_video/*]
Resolve cases of Encountered frames with PSNR less than configured threshold 20.0dB involving c2.intel codecs.
Tracked-On: OAM-118400
=> [c2][encoder] Directly use Y-tiled surface as input for encoder

c2_components/src/mfx_c2_encoder_component.cpp
The BufferSizeInKB is estimated in oneVPL if set to 0 when calling encoder Init(). However, the estimated value is not sufficient in some corner cases, such as HEVC with a bitrate of 4 and a resolution of 176x144. In these cases, set BufferSizeInKB manually to a limit to ensure there is enough space to write the bitstream. cases: android.videocodec.cts.VideoEncoderMinMaxTest#testMinMaxSupport [63_c2.intel.hevc.encoder_video/hevc_0.00mbps_176x144_30fps_maxb-0_vbr_i-dist-0]
Tracked-On: OAM-118627
=> Add minimum limit to BufferSizeInKB for corner cases

c2_buffers/include/mfx_c2_frame_in.h, c2_buffers/include/mfx_c2_frame_out.h, c2_buffers/src/mfx_c2_frame_in.cpp, c2_buffers/src/mfx_c2_frame_out.cpp, c2_components/src/mfx_c2_component.cpp, c2_components/src/mfx_c2_decoder_component.cpp, c2_components/src/mfx_c2_encoder_component.cpp, c2_store/src/mfx_c2_store.cpp, c2_utils/include/mfx_c2_avc_structures.h, c2_utils/include/mfx_c2_hevc_structures.h, c2_utils/include/mfx_cmd_queue.h, c2_utils/include/mfx_gralloc1.h, c2_utils/include/mfx_pool.h, c2_utils/include/mfx_va_frame_pool_allocator.h, c2_utils/src/mfx_frame_constructor.cpp, plugin_store/include/mfx_c2_buffer_queue.h, plugin_store/src/mfx_c2_buffer_queue.cpp
* Uncaught exception
* COPY_INSTEAD_OF_MOVE
* Rule of three
* Logically dead code
Tracked-On: OAM-121342
=> [c2][coverity] Fixed some coverity issues

c2_components/src/mfx_c2_decoder_component.cpp
=> Fix vts regression

c2_components/src/mfx_c2_decoder_component.cpp
=> Fix coverity issue: SIGN_EXTENSION

c2_components/src/mfx_c2_decoder_component.cpp
Include:
Unintended sign extension;
Tracked-On: OAM-129463
=> Refine coverity issue codes

c2_components/src/mfx_c2_decoder_component.cpp, c2_utils/src/mfx_va_frame_pool_allocator.cpp
InCache logic will consume all buffers in buffer pool at same time,
Sometimes encounters stuck issue.
=> Remove InCache logic during initialization of decoder

c2_components/src/mfx_c2_encoder_component.cpp
CTS test of testSimpleEncode failed of: components that support
mediaType: video/x-vnd.on2.vp9 must generate CodecPrivateData.
The cause is: From android V, for VP9 encode, codec private data is required to be updated to framework/app, while there was no such implementation in c2.
The fix is: Referencing libvpx implementation, pass codec private data to framework for VP9 encode.
Tracked-On: OAM-130525
=> Fix CTS issue of VP9 encode no codec private data

c2_components/src/mfx_c2_decoder_component.cpp
Add 'vendor.demo.vppout.transcoding' property in transcoding scenario
Tracked-On: OAM-131801
=> VideoSR Transcoding Demo Support
